POST http://localhost:8080/api/users/458e8649-c4fc-48bf-b7ee-de589e85038f/budgets
Content-Type: application/json

{
    "title": "Monthly spending plan",
    "amountAllocated": "20000",
    "fromDate": "2024-01-01",
    "toDate": "2024-01-31",
    "description": "just to track my monthly expenses"
}