POST http://localhost:8080/api/users/d1f32775-99eb-4046-ae8e-fc25ae4b8c71/budgets
Content-Type: application/json

{
    "title": "Monthly Budget",
    "amountAllocated": "20000",
    "fromDate": "2024-01-01",
    "toDate": "2024-01-31",
    "description": "just to track my monthly expenses"
}