POST http://localhost:8080/api/users/0f4a28e3-11a8-4b7a-97b4-43edbecc96bc/transactions
Content-Type: application/json

{
  "amount": "8700.00",
  "description": "some expense 5",
  "transactionType": "EXPENSE",
  "categoryId": "2315909a-021c-44ad-a3fb-abf0709df490"
}