POST http://localhost:8080/api/users/d1f32775-99eb-4046-ae8e-fc25ae4b8c71/transactions
Content-Type: application/json

{
  "amount": "5100.00",
  "description": "paid for internet",
  "transactionType": "EXPENSE",
  "categoryId": "0a110d7c-b474-49e5-85c0-ca3076a89c28",
  "budgetId": 1
}