PUT http://localhost:8080/api/users/458e8649-c4fc-48bf-b7ee-de589e85038f/transactions/1
Content-Type: application/json

{
  "description": "paid for MTN monthly data",
  "amount": "7500",
  "categoryId": "30dd17c3-9c23-4951-af53-120918723228",
  "transactionType": "EXPENSE"
}