POST http://localhost:8080/api/users/5b37b482-e250-4c2b-9ded-69def2b7b9f9/transactions
Content-Type: application/json

{
  "amount": "136500.00",
  "description": "salary",
  "transactionType": "INCOME"
}