GET http://localhost:8080/api/users/1ed1dbcf-ff09-449e-bfc3-4cd0893ae52d/analytics/monthly-transactions?month=9&year=2025
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzbGFkZUBnbWFpbC5jb20iLCJyb2xlIjoiVXNlciIsImlhdCI6MTc1ODcyNjYwNCwiZXhwIjoxNzU4ODEzMDA0fQ.2AN9zm255fGs6662QTzxBjWElLPp-FpoOvteOTDkOM8