GET http://localhost:8080/api/users/1ed1dbcf-ff09-449e-bfc3-4cd0893ae52d/dashboard
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJzbGFkZUBnbWFpbC5jb20iLCJyb2xlIjoiVXNlciIsImlhdCI6MTc1ODY1NTc2NywiZXhwIjoxNzU4NzQyMTY3fQ.Cm18HPvnHrYQOnQ2xPSxx38fsvz4uzSGpNGGKqGNB74